<?php
$title = 'Users';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?= $this->url('user', ['action' => 'add']) ?>">Add new user</a>
</p>

<table class="table">
    <tr>
        <th>Username</th>
        <th>Pseudo</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->paginator as $user) : ?>
        <tr>
            <td><?= $this->escapeHtml($user->username) ?></td>
            <td><?= $this->escapeHtml($user->pseudo) ?></td>
            <td>
                <a href="<?= $this->url('user', ['action' => 'edit', 'id' => $user->id]) ?>">Edit</a>
                <a href="<?= $this->url('user', ['action' => 'delete', 'id' => $user->id]) ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<?= $this->paginationControl(
    // The paginator object:
    $this->paginator,
    // The scrolling style:
    'sliding',
    // The partial to use to render the control:
    'partial/paginator',
    // The route to link to when a user clicks a control link:
    ['route' => 'user']
) ?>