<?php
$user = $this->user;
$title = 'User ' . $user->pseudo;
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title); ?></h1>

<table class="table">
    <tr>
        <td><b>Pseudo</b></td>
        <td><?= $this->user->pseudo ?></td>
    </tr>
    <tr>
        <td><b>Inscription</b></td>
        <td><?= $this->user->inscriptionDate ?></td>
    </tr>
    <?php if($this->user->username == $_SESSION['user']->username) : ?>
    <tr>
        <td>
            <a href="<?= $this->url('user', ['action' => 'edit']) ?>">
                <input class="btn btn-primary" type="button" value="Edit" />
            </a>
        </td>
        <td></td>
    </tr>
    <?php endif; ?>
</table>