<?= $this->doctype() ?>
<?php //print_r($this); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/base.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="http://noctuce.ca/wp-content/themes/Noctuce/assets/images/Signature.svg" height="28" />
                    </a>
                </div>
                <div class="collapse navbar-collapse links-bar" style="display:inline-block !important;">
                    <?= $this->navigation('Zend\Navigation\Default')
                        ->menu()
                        ->setMinDepth(0)
                        ->setMaxDepth(0)
                        ->setUlClass('nav navbar-nav') ?>
                </div>
                <div style="display:inline-block; float:right;">
                    <ul class="nav navbar-nav navbar-user">
                    <?php $user = $_SESSION['user'];
                        if (isset($_SESSION['user'])) : ?>
                        <li>
                            <a href="<?= $this->url('user') ?>">
                                <?= $_SESSION['user']->username ?>
                            </a>
                            <ul>
                                <li>
                                    <a href="" ?>
                                        Logout
                                    </a>
                                </li>
                            </ul>
                        </li>
                    <?php else: ?>
                        <li>
                            <a href="<?= $this->url('user') ?>">
                                Login / Subscribe
                            </a>
                        </li>
                    <?php endif; ?>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->navigation('navigation')
                    ->breadcrumbs()
                    ->setMinDepth(0)
                    ->setPartial('partial/breadcrumb') ?>
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
